compiler:
  - clang
  - gcc

script:
  # скрипт сборки и тестирования проекта:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
